### ISSUE TITLE
Syntax error VScode

### ISSUE THREAD

**Issue by extragornax** [wakatime/legacy-python-cli#133]
Hello,

I didn't find an issue similar yet
I'm running windows 10 dev mode Up to date
Vscode up to date
Python 3.6 as default

this issue is also on sublime for me

I get this error everytime
![ulhsm5q](https://user-images.githubusercontent.com/522344/39133986-5fadac64-46ca-11e8-9099-b6abc11cc03e.png)

Does anyone know why ?
The same command works in Powershell oddly

Thank you

**Comment by alanhamlett** [comment]
The problem is Python 3.2, which is not supported for WakaTime plugins. You can downgrade to Python 2.7 or upgrade to Python 3.3 or newer and the error will go away.

**Comment by extragornax** [comment]
@alanhamlett Hello, my default python version is 3.6. How can I make the plugin also use it as default ? VScode uses the 3.6 one but not the extension.
